plugins { id 'com.android.application' }

android {
    namespace 'dev.local.nativemacrohelper'
    compileSdk 36
    defaultConfig {
        applicationId 'dev.local.nativemacrohelper'
        minSdk 29
        targetSdk 36
        versionCode 8
        versionName '1.1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
